# Generated by Django 2.1.7 on 2019-05-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='messages',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
